### PR TITLE
Add testing of controllers

### PR DESCRIPTION
**Pull request by aaronnorby**
These tests look at searchController and LandingController

### CODE REVIEW

**Comment by aaronnorby** [comment]
@sndsgn @dutchers @PhongHPham if one of you wants to merge this in - testing the controllers (some of them)

**Comment by sndsgn** [comment]
I will merge it in.

**Comment by sndsgn** [comment]
Looks good.

**Comment by phonghpham** [comment]
@aaronnorby, nice one, doc !

**Pull request merged**
